<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Elemento raíz -->
    <xs:element name="boleibol_federazioa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="taldeak">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="taldea" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="taldeIzena" type="xs:string"/>
                                        <xs:element name="taldeLogoa" type="xs:string"/>
                                        <xs:element name="taldeDeskribapena" type="xs:string"/>
                                        <xs:element name="taldeLehendakaria" type="xs:string"/>
                                        <xs:element name="taldeSorrera" type="xs:gYear"/>
                                        <xs:element name="taldeZelaia" type="xs:string"/>
                                        <xs:element name="jokalariak">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="jokalaria" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="jokalariZbk" type="xs:positiveInteger" minOccurs="0"/>
                                                                <xs:element name="jokalariIzenAbizena" type="xs:string" minOccurs="0"/>
                                                                <xs:element name="jokalariAdina" type="xs:integer" minOccurs="0"/>
                                                                <xs:element name="generoa" type="xs:string" minOccurs="0"/>
                                                                <xs:element name="jokalariPosizioa" type="xs:string" minOccurs="0"/>                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
